// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQrm2N_am43cLS0L94PztEE8oYVEMbSwY',
    appId: '1:830415187014:web:c3e8bba457632a146fae47',
    messagingSenderId: '830415187014',
    projectId: 'fyp2-c97ef',
    authDomain: 'fyp2-c97ef.firebaseapp.com',
    storageBucket: 'fyp2-c97ef.appspot.com',
    measurementId: 'G-QV4ZP89K40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO8MytZoUtkdDoDtzSRyRdaERtBaByt7M',
    appId: '1:830415187014:android:d7db62e1aedea13c6fae47',
    messagingSenderId: '830415187014',
    projectId: 'fyp2-c97ef',
    storageBucket: 'fyp2-c97ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7wLluqACEz3Ku2CLywFwrcl1QZ2BZTsg',
    appId: '1:830415187014:ios:30861080d9a0e5fc6fae47',
    messagingSenderId: '830415187014',
    projectId: 'fyp2-c97ef',
    storageBucket: 'fyp2-c97ef.appspot.com',
    iosBundleId: 'com.example.eWellness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7wLluqACEz3Ku2CLywFwrcl1QZ2BZTsg',
    appId: '1:830415187014:ios:1b5e7a7354574e2f6fae47',
    messagingSenderId: '830415187014',
    projectId: 'fyp2-c97ef',
    storageBucket: 'fyp2-c97ef.appspot.com',
    iosBundleId: 'com.example.eWellness.RunnerTests',
  );
}
